# Generated by Django 5.1 on 2024-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_disponible_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
