# Generated by Django 5.1 on 2024-09-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
