# Generated by Django 5.1 on 2024-09-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_productocategoria_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='servicio',
            new_name='producto',
        ),
    ]
