# Generated by Django 5.1 on 2024-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
