# Generated by Django 5.1 on 2024-09-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_rename_producto_pedido_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='categoria_nombre',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='productos_p_nombre_456643_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_de_medida',
        ),
    ]
