# Generated by Django 5.1 on 2024-09-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
