# Generated by Django 5.1 on 2024-09-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
    ]
