# Generated by Django 5.1 on 2024-09-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='servicio',
            new_name='producto',
        ),
    ]
