# Generated by Django 5.1.1 on 2024-09-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_productocategoria_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='producto',
        ),
    ]
