# Generated by Django 5.1.1 on 2024-09-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_rename_nombre_producto_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='servicio',
            new_name='producto',
        ),
    ]
