# Generated by Django 5.1 on 2024-09-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_rename_servicio_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='producto',
            new_name='servicio',
        ),
    ]
