# Generated by Django 5.1.1 on 2024-09-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_rename_producto_pedido_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='servicio',
            new_name='producto',
        ),
    ]
