# Generated by Django 5.1.1 on 2024-09-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_rename_servicio_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
    ]
